### ISSUE TITLE
NAV FOR A SPECIFIC ISIN

### ISSUE THREAD

**Issue by paras03** [ankitwasankar/mftool-java#3]
There are scheme code which has multiple isin, how does one fetch NAV for a specific ISIN.
FOR EXAMPLE
Scheme code : 100034
Scheme name : Aditya Birla Sun Life Equity Advantage Fund -Regular - IDCW

ISIN attached to this scheme code :
INF209K01157 and INF209K01CE5

ISIN Div Payout/ ISIN Growth  ISIN Div Reinvestment

Thanks 

Paras

**Comment by ankitwasankar** [comment]
Are you sure the NAV is going to be different ? Just checked on https://www.amfiindia.com - the NAV for the same product with 2 different ISIN are same.

![image](https://github.com/user-attachments/assets/1ace0aa6-9894-4150-9a39-0184231a3638)

**Comment by paras03** [comment]
Thanks for your feedback.
So far i understand, the NAV of Direct Growth and Regular Growth is different, though the scheme number is the same, Following is the explanation.

In regular fund, there is an expense in terms of distributor commission, which is not there in Direct Fund.

Now NAV = (market value of securities in portfolio - expenses) / number of mutual fund units

So, the NAV of Direct fund is supposed to be higher than regular fund.

So ideally NAV should be populated as per ISIN, which is a unique identity of each security.
, 
Please correct me if my understanding is wrong.

Thanks

Paras

**Comment by ankitwasankar** [comment]
NAV is an attribute which is present at scheme level that is at `schemeCode` level.
The `schemeCode` can have different ISIN 1) **ISIN Div Payout** and 2) **ISIN Div Reinvestment** type, but the NAV is going to be same for both ISIN because they belong to the same `schemeCode`.

**In your example:**
Scheme code : 100034
This scheme has 2 different ISIN 1) **ISIN Div Payout** and 2) **ISIN Div Reinvestment**
Althouth the scheme has 2 different ISIN, it will have same NAV because they belong to same scheme.

Can you please give me an example, where you see different NAV ? (I don't think that will be the case)

**In you above query:**
You said about direct and regular funds -- but they will always have different scheme codes. So It should not be an issue.
Can you please provide an example please if you see this with direct/indirect fund.

**Here is the screenshot for your reference:**
A direct scheme is divided into 2 different categories, but both have the same NAV
![image](https://github.com/user-attachments/assets/d156e6c6-b3be-4014-8f7a-1c3665093209)

**Comment by paras03** [comment]
Thanks
You are right, the NAV remains same (reduced by dividend amount) only no of units increases in dividend Reinvestment.
Thanks for taking time for clarifying and exemplifying.
My best regards
Paras
